SportFixtureTracking/Models/Fixture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace SportFixtureTracking.Models
{
    public partial class Fixture
    {
        public Fixture()
        {
            FixtureResults = new HashSet<FixtureResult>();
        }
       
        public int FixtureId { get; set; }

        [Required(ErrorMessage = "Date con not be empty")]
        public DateTime FixtureDate { get; set; }

        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }

        [Required(ErrorMessage = "Home con not be empty")]
        [MaxLength(50,ErrorMessage = "Home shoukd be shorter than 50 character")]
        public string FixtureHome { get; set; }

        [StringLength(1,ErrorMessage ="Write N for Not Finished, Y For Finished")]
        public string IsFinished { get; set; }

        public virtual Team AwayTeam { get; set; }
        public virtual Team HomeTeam { get; set; }
        public virtual ICollection<FixtureResult> FixtureResults { get; set; }
    }
}

SportFixtureTracking/Controllers/FixtureResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportFixtureTracking.Models;

namespace SportFixtureTracking.Controllers
{
    public class FixtureResultsController : Controller
    {
        private readonly SportFixturePointContext _context;

        public FixtureResultsController(SportFixturePointContext context)
        {
            _context = context;
        }

        // GET: FixtureResults
        public async Task<IActionResult> Index()
        {
            var sportFixturePointContext = _context.FixtureResults.Include(f => f.Fixture).ThenInclude(f => f.AwayTeam).Include(f=>f.Fixture.HomeTeam)
                .Include(f => f.WinnerTeam);
            return View(await sportFixturePointContext.ToListAsync());
        }

        // GET: FixtureResults/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var fixtureResult = await _context.FixtureResults.FindAsync(id);
            var fixtureResult = await _context.FixtureResults.Include(f => f.Fixture).ThenInclude(f => f.AwayTeam).Include(f => f.Fixture.HomeTeam)
                .Include(f => f.WinnerTeam).FirstOrDefaultAsync(r=> r.ResultId == id);
            if (fixtureResult == null)
            {
                return NotFound();
            }
            ViewData["WinnerTeamId"] = new SelectList(_context.Teams.Where(f => f.TeamId == fixtureResult.Fixture.AwayTeamId || f.TeamId == fixtureResult.Fixture.HomeTeamId), "TeamId", "TeamName", fixtureResult.WinnerTeamId);
            return View(fixtureResult);
        }

        // POST: FixtureResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResultId,FixtureId,HomeTeamScore,AwayTeamScore,WinnerTeamId")] FixtureResult fixtureResult)
        {
            if (id != fixtureResult.ResultId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fixtureResult);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FixtureResultExists(fixtureResult.ResultId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FixtureId"] = new SelectList(_context.Fixtures, "FixtureId", "IsFinished", fixtureResult.Fixture_Id);
            ViewData["WinnerTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixtureResult.WinnerTeamId);
            return View(fixtureResult);
        }

        public async Task<IActionResult> Point()
        {
            var sportFixturePointContext = await _context.FixtureResults.Include(f => f.Fixture).ThenInclude(f => f.AwayTeam).Include(f => f.Fixture.HomeTeam)
                .Include(f => f.WinnerTeam).ToListAsync();
            var teamTotalPoints = new Dictionary<Team, int>();
           
          
            foreach(var item in sportFixturePointContext)
            {
                if(teamTotalPoints.ContainsKey(item.Fixture.AwayTeam))
                {
                    teamTotalPoints[item.Fixture.AwayTeam] = teamTotalPoints[item.Fixture.AwayTeam] + Convert.ToInt32(item.AwayTeamScore);
                }
                else
                {
                    teamTotalPoints[item.Fixture.AwayTeam] = Convert.ToInt32(item.AwayTeamScore);
                }
                if(teamTotalPoints.ContainsKey(item.Fixture.HomeTeam))
                {
                    teamTotalPoints[item.Fixture.HomeTeam] = teamTotalPoints[item.Fixture.HomeTeam] + Convert.ToInt32(item.HomeTeamScore);
                }
                else
                {
                    teamTotalPoints[item.Fixture.HomeTeam] = Convert.ToInt32(item.HomeTeamScore);
                }
            }
           
            ViewData["TeamPointPairs"] = teamTotalPoints;
            return View(nameof(Point));
        }

        private bool FixtureResultExists(int id)
        {
            return _context.FixtureResults.Any(e => e.ResultId == id);
        }
    }
}

SportFixtureTracking/Controllers/FixturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportFixtureTracking.Models;

namespace SportFixtureTracking.Controllers
{
    public class FixturesController : Controller
    {
        private readonly SportFixturePointContext _context;

        public FixturesController(SportFixturePointContext context)
        {
            _context = context;
        }

        // GET: Fixtures
        public async Task<IActionResult> Index()
        {
            
            var sportFixturePointContext = _context.Fixtures.Include(f => f.AwayTeam).Include(f => f.HomeTeam).Include(r=>r.FixtureResults);
            return View(await sportFixturePointContext.ToListAsync());
        }
  
        // GET: Fixtures/Create
        public IActionResult Create()
        {
            ViewData["AwayTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName");
            ViewData["HomeTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName");
            return View();
        }

        // POST: Fixtures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public async Task<IActionResult> Create([Bind("FixtureId,FixtureDate,HomeTeamId,AwayTeamId,FixtureHome")] Fixture fixture)
        {
            var homeTeam = _context.Teams.Where(r=>  r.TeamId == fixture.HomeTeamId).FirstOrDefault();
            var awayTeam = _context.Teams.Where(r => r.TeamId == fixture.AwayTeamId).FirstOrDefault();
            if(homeTeam.SportId != awayTeam.SportId)
            {
                return NotFound();
            }
            fixture.IsFinished = "N";
            if (ModelState.IsValid)
            {
                _context.Add(fixture);
               
                await _context.SaveChangesAsync();
                return AlsoAddFixtureResult(fixture);
                //return RedirectToAction(nameof(Index));
            }
            
            ViewData["AwayTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.AwayTeamId);
            ViewData["HomeTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.HomeTeamId);
            return View(fixture);
        }

        public IActionResult AlsoAddFixtureResult(Fixture fixture)
        {
            FixtureResult f = new FixtureResult { ResultId = 0, Fixture_Id = fixture.FixtureId, AwayTeamScore = 0, HomeTeamScore = 0 };
            if(ModelState.IsValid)
            {
                _context.Add(f);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        
        // GET: Fixtures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fixture = await _context.Fixtures.Include(r => r.AwayTeam).Include(s => s.HomeTeam).FirstOrDefaultAsync(a => a.FixtureId == id);
            if (fixture == null)
            {
                return NotFound();
            }
            ViewData["AwayTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.AwayTeamId);
            ViewData["HomeTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.HomeTeamId);
            return View(fixture);
        }

        // POST: Fixtures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FixtureId,FixtureDate,HomeTeamId,AwayTeamId,FixtureHome,IsFinished")] Fixture fixture)
        {
            if (id != fixture.FixtureId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fixture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FixtureExists(fixture.FixtureId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AwayTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.AwayTeamId);
            ViewData["HomeTeamId"] = new SelectList(_context.Teams, "TeamId", "TeamName", fixture.HomeTeamId);
            return View(fixture);
        }

        // GET: Fixtures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fixture = await _context.Fixtures
                .Include(f => f.AwayTeam)
                .Include(f => f.HomeTeam)
                .FirstOrDefaultAsync(m => m.FixtureId == id);
            if (fixture == null)
            {
                return NotFound();
            }

            return View(fixture);
        }

        // POST: Fixtures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var fixture = await _context.Fixtures.FindAsync(id);
            DeleteFixtureResultByFixtureId(fixture.FixtureId);
            _context.Fixtures.Remove(fixture);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private void DeleteFixtureResultByFixtureId(int id)
        {
            var result = _context.FixtureResults.FirstOrDefault(r=> r.Fixture_Id == id);
            _context.FixtureResults.Remove(result);
        }
        private bool FixtureExists(int id)
        {
            return _context.Fixtures.Any(e => e.FixtureId == id);
        }
    }
}

SportFixtureTracking/Views/Fixtures/Create.cshtml
@model SportFixtureTracking.Models.Fixture

@{
    ViewData["Title"] = "Create";
}

<div class="d-flex justify-content-center align-items-center h-100">
    <h1 class="mb-3" style="color:aliceblue">Creating New Fixture</h1>

</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FixtureDate" class="control-label" style="color:aliceblue">Date</label>
                <input asp-for="FixtureDate" class="form-control" />
                <span asp-validation-for="FixtureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeTeamId" class="control-label" style="color:aliceblue">Home Team</label>
                <select asp-for="HomeTeamId" class ="form-control" asp-items="ViewBag.HomeTeamId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AwayTeamId" class="control-label" style="color:aliceblue">Away Team</label>
                <select asp-for="AwayTeamId" class ="form-control" asp-items="ViewBag.AwayTeamId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FixtureHome" class="control-label" style="color:aliceblue">Home</label>
                <input asp-for="FixtureHome" class="form-control" />
                <span asp-validation-for="FixtureHome" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-info mr-3" />
                <a asp-action="Index">
                    <i class="fas fa-reply" style="color:coral"></i>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportFixtureTracking/Views/Fixtures/Delete.cshtml
@model SportFixtureTracking.Models.Fixture

@{
    ViewData["Title"] = "Delete";
}


<div class="d-flex justify-content-center align-items-center h-100">
    <h1 class="mb-3" style="color:aliceblue">Deleting @Model.HomeTeam.TeamName - @Model.AwayTeam.TeamName </h1>

</div>
<div>
    <h4>Fixture</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2" style="color:aliceblue">
            Date
        </dt>
        <dd class="col-sm-10" style="color:#9d9d9d">
            @Html.DisplayFor(model => model.FixtureDate)
        </dd>
        <dt class="col-sm-2" style="color:aliceblue">
            Home
        </dt>
        <dd class="col-sm-10" style="color:#9d9d9d">
            @Html.DisplayFor(model => model.FixtureHome)
        </dd>
        <dt class="col-sm-2" style="color:aliceblue">
            Finished
        </dt>
        <dd class="col-sm-10" style="color:#9d9d9d">

            @{ if (Model.IsFinished.Contains('Y'))
                {
                    <i class="fas fa-check" style="color:#26b118"></i>
                }
                else
                {
                    <i class="fas fa-times" style="color:#e44141"></i>
                }
            }
        </dd>
        <dt class="col-sm-2" style="color:aliceblue">
            Away Team
        </dt>
        <dd class="col-sm-10" style="color:#9d9d9d">
            @Html.DisplayFor(model => model.AwayTeam.TeamName)
        </dd>
        <dt class="col-sm-2" style="color:aliceblue">
            Home Team
        </dt>
        <dd class="col-sm-10" style="color:#9d9d9d">
            @Html.DisplayFor(model => model.HomeTeam.TeamName)
        </dd>
    </dl>

    <form asp-action="Delete" class="d-flex justify-content-center align-items-center h-100">
        <input type="hidden" asp-for="FixtureId" />
        <input type="submit" value="Delete" class="btn btn-danger" style="margin-right:50px;"/>
        <a asp-action="Index">
            <i class="fas fa-reply" style="color:coral"></i>
        </a>
    </form>
</div>

SportFixtureTracking/Views/Fixtures/Edit.cshtml
@model SportFixtureTracking.Models.Fixture

@{
    ViewData["Title"] = "Edit";
}

<<div class="d-flex justify-content-center align-items-center h-100">
    <h1 class="mb-3" style="color:aliceblue">Editing @Model.HomeTeam.TeamName - @Model.AwayTeam.TeamName</h1>

</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FixtureId" />
            <div class="form-group">
                <label asp-for="FixtureDate" class="control-label" style="color:aliceblue;text-align:center">Date</label>
                <input asp-for="FixtureDate" class="form-control" />
                <span asp-validation-for="FixtureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeTeamId" class="control-label" style="color:aliceblue;text-align:center">Home Team</label>
                <select asp-for="HomeTeamId" class="form-control" asp-items="ViewBag.HomeTeamId"></select>
                <span asp-validation-for="HomeTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwayTeamId" class="control-label" style="color:aliceblue;text-align:center">Away Team</label>
                <select asp-for="AwayTeamId" class="form-control" asp-items="ViewBag.AwayTeamId"></select>
                <span asp-validation-for="AwayTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FixtureHome" class="control-label" style="color:aliceblue;text-align:center">Home</label>
                <input asp-for="FixtureHome" class="form-control" />
                <span asp-validation-for="FixtureHome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsFinished" class="control-label" style="color:aliceblue;text-align:center">Finished(Y or N)</label>
                <input asp-for="IsFinished" class="form-control" />
                <span asp-validation-for="IsFinished" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info mr-3" />
                <a asp-action="Index">
                    <i class="fas fa-reply" style="color:coral"></i>
                </a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportFixtureTracking/Views/Fixtures/Index.cshtml
@model IEnumerable<SportFixtureTracking.Models.Fixture>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex justify-content-center align-items-center h-100">
    <h1 class="mb-3" style="color:aliceblue">Fixtures</h1>

</div>
<div class="form-inline">
@foreach (var item in Model) {

    <div class="card text-center" style="background-color:#272727;color:aliceblue;margin-left:10px;margin-bottom:10px;" >
        <div class="card-header">
            @item.FixtureDate.ToString("dddd, dd MMMM")
            
        </div>
        <div class="card-body" style="background-color:#272727;">
            <h5 class="card-title">
                @item.HomeTeam.TeamName - @item.AwayTeam.TeamName 
            </h5>
            <p class="card-text text-muted">
                @item.FixtureHome
            </p>
            <p>
                <a asp-action="Edit" asp-route-id="@item.FixtureId">
                    <i class="fas fa-edit" style="color:#c6ab19"></i>
                </a> |
                <a asp-action="Delete" asp-route-id="@item.FixtureId">
                    <i class="fas fa-trash-alt" style="color:#bb3939"></i>
                </a>
            </p>
        </div>
        <div class="card-footer text-muted">

            @{ if (DateTime.Compare(item.FixtureDate, DateTime.Now) > 0)
                { // if fixture date is later than now,
                    <p>
                        After @DateTime.Now.Subtract(item.FixtureDate).ToString("dd") Day
                    </p>
                }

                else if (DateTime.Compare(item.FixtureDate, DateTime.Now) == 0)
                {
                    <p>
                        Today
                    </p>
                }
                else if (DateTime.Compare(item.FixtureDate, DateTime.Now) < 0)
                {
                    <p >
                        @DateTime.Now.Subtract(item.FixtureDate).ToString("dd") Day Ago 
                        -
                        
                        <a asp-action="Index" asp-route-id="" asp-controller="FixtureResults" style="color:#c6ab19;">
                            View Result
                        </a>
                    </p>
                }
            }


        </div>
    </div>
}
 </div>
   
<div class="d-flex justify-content-center align-items-center h-100">
    <a asp-action="Create" style="color: #c6ab19; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; ">
        <i class="fas fa-plus fa-1x" style="color: #c6ab19;"></i> New
    </a>
</div>